name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.bakcup.calisto.link
          username: ysn@bakcup.calistodigital.com
          password: "X$n!]S0?vVQB"
          protocol: sftp  # Eğer sunucu sadece SFTP destekliyorsa
          port: 22  # SFTP için genellikle 22, FTP için 21 kullanılır
          local-dir: ./
          server-dir: public_html
          log-level: verbose  # Detaylı log almak için
